### ISSUE TITLE
[Bug]: [1.21] Neoforge and elytra slot crash on latest version

### ISSUE THREAD

**Issue by Periam** [TheIllusiveC4/CuriousElytra#122] opened 2024-07-20 16:17 UTC
### Minecraft Version

1.21.0

### What happened?

The game crashed when starting in the loading screen

### How do you trigger this bug?

1.Install the Mod 
2. Install depencies
3. Instal JEI
4.Launch the game
...

### Loader

Forge

### Loader Version

NeoForge 21.0.113

### Mod Version

Eletra Slot neoforge 19.5.0.44

### Relevant Log Outputs

[debug.log](https://github.com/user-attachments/files/16321667/debug.log)
[latest.log](https://github.com/user-attachments/files/16321668/latest.log)
[crash-2024-07-20_13.14.43-fml.txt](https://github.com/user-attachments/files/16321670/crash-2024-07-20_13.14.43-fml.txt)

![image](https://github.com/user-attachments/assets/f0bbe087-4837-443d-a6fa-a34d25537f7f)

**Comment by TheIllusiveC4** [comment] 2024-07-20 21:52
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/121
This is a Customizable Elytra issue.

**Closed as not planned by TheIllusiveC4** 2024-07-20 21:52 UTC
Labels: type: bug, status: duplicate
