### ISSUE TITLE
[Feature]: Mention that Caelus API is needed on the mod page

### ISSUE THREAD

**Issue by Catoumy** [TheIllusiveC4/CuriousElytra#93] opened 2023-11-01 01:35 UTC
### What is the new feature or improvement?

After 30 minutes of back and forth trying to figure out why the elytraslot mod was crashing my server
i find out after opening minecraft and trying to join the server with the mod DISABLED on both server and client
that Caelus API was also downloaded on my client without me knowing (curseforge app).

**Comment by TheIllusiveC4** [comment] 2024-06-07 05:14
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/80

**Closed as not planned by TheIllusiveC4** 2024-06-07 05:14 UTC
Labels: status: duplicate, type: enhancement
