### ISSUE TITLE
compatibility with Tinkers Construct mod  (slime elytra)

### ISSUE THREAD

**Issue by EvilToasterDBU** [TheIllusiveC4/CuriousElytra#52] opened 2022-09-15 16:35 UTC
Please add support slime elytra from Tinkers Construct mod (1.16.5+)

**Comment by Landrozaum** [comment] 2022-09-15 18:32
i think he will not but i wait this also (last 1.18 update was in january)

**Comment by TheIllusiveC4** [comment] 2022-12-23 13:49
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/43

**Closed as not planned by TheIllusiveC4** 2022-12-23 13:49 UTC
Labels: status: duplicate, type: enhancement
