### ISSUE TITLE
[Feature]: Tinkers Construct / Hephaestus support

### ISSUE THREAD

**Issue by SexyAnimeLady** [TheIllusiveC4/CuriousElytra#137] opened 2024-10-05 21:51 UTC
### What is the new feature or improvement?

Add support for the item Slimelytra from the [Tinkers Construct mod](https://modrinth.com/mod/tinkers-construct) and it's fabric port [Hephaestus](https://modrinth.com/mod/hephaestus). Both mods seemingly use the same assets/terms/etc outside of the general launcher differences.

**Comment by TheIllusiveC4** [comment] 2024-10-06 23:58
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/43

**Closed as not planned by TheIllusiveC4** 2024-10-06 23:58 UTC
Labels: status: duplicate, type: enhancement
